name: Reusable build image

on:
  workflow_call:
    inputs:
      ecr-repo:
        type: string
        description: "ECR Respoitory"
        required: true
      image-name:
        type: string
        description: "Image Name"
        required: true
      working-directory:
        type: string
        description: "Working directory"
        required: true
      build-options:
        type: string
        description: "Docker build options if needed"
        default: ""
        required: false
      test-image:
        type: boolean
        description: "Test the built image"
        default: false
        required: false
      test-image-config:
        type: string
        description: "Full path to container-structure-test config file"
        default: ''
        required: false
    secrets:
      aws-access-key-id:
        description: "AWS access key ID"
        required: true
      aws-secret-access-key:
        description: "AWS secret access key"
        required: true

jobs:
  build-image:
    name: 'Build image'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        env:
          GIT_SHA: ${{ github.sha }}
          DOCKER_BUILDKIT: 1
        run: |
          docker build \
          --pull \
          --no-cache \ 
          ${{ build-options }} \
          --file ${{ inputs.working-directory }}/Dockerfile \
          -t ${{ inputs.ecr-registry }}/${{ inputs.image-name }}:${GIT_SHA:0:7} \
          -t ${{ inputs.ecr-registry }}/${{ inputs.image-name }}:latest \
          ${{ inputs.working-directory }}

      - name: Run container tests
        if: inputs.test-image == true && inputs.test-image-config != ''
        env:
          GIT_SHA: ${{ github.sha }}
        run: |
          curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64 \
          && chmod +x container-structure-test-linux-amd64 \
          && mkdir -p $HOME/bin \
          && export PATH=$PATH:$HOME/bin \
          && mv container-structure-test-linux-amd64 $HOME/bin/container-structure-test\
          && container-structure-test test -c ${{ inputs.test-image-config }} -i ${{ inputs.ecr-registry }}/${{ inputs.image-name }}:latest
          && container-structure-test test -c ${{ inputs.test-image-config }} -i ${{ inputs.ecr-registry }}/${{ inputs.image-name }}:${GIT_SHA:0:7}